# Generated by Django 5.1.4 on 2025-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
